### ISSUE TITLE
Don't working in 20.0-ALPHA1 (19.90.101) Git:20220125-e60e5c24bf

### ISSUE THREAD

**Issue by loly-girl** [add-ons/script.speedtester#23]
Runs well. However, when I run the test, only the ping is detected. There are no other visual changes. The log has the following error:

```
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: 'Thread' object has no attribute 'isAlive'
Traceback (most recent call last):
 File "/home/loly/.kodi/addons/script.speedtester/resources/lib/addon.py", line 658, in onClick
   self.speedtest(share=True, simple=True)
 File "/home/loly/.kodi/addons/script.speedtester/resources/lib/addon.py", line 860, in speedtest
   dlspeed = self.download_speed(urls, simple)
 File "/home/loly/.kodi/addons/script.speedtester/resources/lib/addon.py", line 752, in download_speed
   while prod_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
-->End of Python script error report<--

```
https://github.com/add-ons/script.speedtester/files/7936480/fragment.log

**Comment by dagwieers** [comment]
Is it possible you are running an older version?
This has been fixed in #22 and released as v1.1.3.

**Comment by dagwieers** [comment]
And then I noticed that we never actually released v1.1.3 :-/

**Comment by dagwieers** [comment]
Fixed in #24

**Comment by dagwieers** [comment]
Thanks for reporting !

**Comment by pitsi** [comment]
I am facing the same issue on kodi 20a1. I installed the latest libreelec 11 nightly yesterday (now on python 3.9.x) so as to check on kodi 20a1 and I noticed that the addon does not work there, but behaves as mentioned at the start.

I know that v1.1.3 is available through github and I can download it and install it from zip, but can you please add it on the main repo too? Because, as seen below, it is still on v1.1.2 there. 
https://mirrors.kodi.tv/addons/nexus/script.speedtester/

Plus, the same version is listed as the latest for kodi 18 and 19
https://mirrors.kodi.tv/addons/matrix/script.speedtester/
https://mirrors.kodi.tv/addons/leia/script.speedtester/
